### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by KentaroKageyama** [Taroon29/furima-35204#9]
#自身のフリマアプリのURL 
https://furima-35204.herokuapp.com/

#Basic認証のIDとパスワード 
ID: admin
password: 1234

#出品者用のメールアドレスとパスワード
email: a@b
password: 123abc

#購入者用のメールアドレスとパスワード 
email: b@c
password: 123abc

**Comment by takumi0530** [comment]
@Taroon29 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/113253602-68a72680-9300-11eb-8f2a-01d5529bff1c.png)
